name: Get Unity license activation file ğŸ”

on: workflow_dispatch

jobs:
  activateLicense:
    name: Activate Unity licensing ğŸ”‘
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
